name: Build

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o dist/GoMemoryEditor.exe ./cmd

    - name: Upload a Windows Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GoMemoryEditor
        path: dist/GoMemoryEditor.exe
